require:
  - rubocop-performance
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

Rails:
  Enabled: true

AllCops:
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*


Documentation:
  Enabled: false


HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: false
