require:
  - rubocop-performance
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

Rails:
  Enabled: true

AllCops:
  Exclude:
    - spec/support/*
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - Guardfile


Documentation:
  Enabled: false

Lint/Void:
  Exclude:
    - spec/support/**/*

HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: false


