language: ruby
cache: bundler
services:
  - postgresql
before_script:
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
script:
  - bundle exec rubocop
  - bundle exec rspec
notifications:
  email: false

deploy:
  provider: script
  script: "./build.sh"
  on:
    all_branches: true