default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: maap-store_development

test:
  <<: *default
  database: maap-store_test

production:
  <<: *default
  database: maap-store_production
  username: maap-store
  password: <%= ENV['MAAP-STORE_DATABASE_PASSWORD'] %>
